on:
  pull_request: 
        types:
         - opened

jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Post PR Comment
      uses: sidd-harth-1/docker-action-giphy-pr-comment@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

    - name: Post Javascript PR Comment
      uses: sidd-harth-1/js-action-pr-giphy-comment@1.0.0-alpha
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
